package com.demo.spring_crud.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "users") // Use a different name like "users"
public class User {

    @Id
    @GeneratedValue
    private Integer id; // Automatically generated by the database
    private String name;
    private Integer age;
    private String address;

    // Explicitly add the setter method for 'id'
    public void setId(Integer id) {
        this.id = id;
    }

    // Explicitly add the setter method for 'name'
    public void setName(String name) {
        this.name = name;
    }
}
